# golangci-lint configuration for ReleasePilot
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - plugins/gitlab  # Temporarily disabled - needs migration to new GitLab SDK

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/felixgeelhaar/release-pilot

linters:
  enable:
    # Default linters
    - staticcheck  # Includes gosimple and unused in v2
    - ineffassign

    # Additional recommended linters
    - bodyclose
    - contextcheck
    - errname
    - goprintffuncname
    - misspell
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - whitespace

  disable:
    - gochecknoglobals  # We use globals for version info
    - exhaustruct       # Too strict for our use case
    - varnamelen        # Too strict
    - ireturn           # Interfaces are fine to return
    - nonamedreturns    # Named returns are useful in some cases
    - wsl               # Too opinionated
    - gosec             # TODO: Re-enable and fix security issues
    - errcheck          # TODO: Re-enable and fix unchecked errors
    - errorlint         # TODO: Re-enable and fix error wrapping
    - revive            # TODO: Re-enable and fix style issues
    - nolintlint        # Disabled until other linters are fixed
    - govet             # TODO: Re-enable after fixing shadow issues

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for readability

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104  # Audit errors not checked (we handle this with errcheck)
        - G304  # Potential file inclusion via variable (needed for config)

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    # Ignore deprecated GitLab SDK warnings - plugin temporarily disabled pending migration
    - path: plugins/gitlab/
      linters:
        - staticcheck
      text: "SA1019.*gitlab"
