# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for Relicta
# Handles cross-platform builds while Relicta manages release governance

version: 2

project_name: relicta

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: relicta
    main: ./cmd/relicta
    binary: relicta
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.ver={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  # Changelog is generated by Relicta, not GoReleaser
  disable: true

release:
  # GitHub release is created by Relicta's github plugin
  # GoReleaser only builds and uploads artifacts
  draft: false
  prerelease: auto
  mode: keep-existing

# Homebrew formula
brews:
  - name: relicta
    repository:
      owner: relicta-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/relicta-tech/relicta"
    description: "AI-powered release governance for modern software teams"
    license: "MIT"
    install: |
      bin.install "relicta"
    test: |
      system "#{bin}/relicta", "version"
    skip_upload: auto

# SBOM generation
sboms:
  - artifacts: archive

# Sign checksums
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes
    artifacts: checksum
    output: true
