# GoReleaser configuration for Relicta
# https://goreleaser.com/customization/

version: 2

project_name: relicta

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # Main CLI binary
  - id: relicta
    main: ./cmd/relicta
    binary: relicta
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  # GitHub plugin - named to match installer expectations: {plugin}_{os}_{arch}
  - id: plugin-github
    main: ./plugins/github
    binary: github_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # npm plugin
  - id: plugin-npm
    main: ./plugins/npm
    binary: npm_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # Slack plugin
  - id: plugin-slack
    main: ./plugins/slack
    binary: slack_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # Discord plugin
  - id: plugin-discord
    main: ./plugins/discord
    binary: discord_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # LaunchNotes plugin
  - id: plugin-launchnotes
    main: ./plugins/launchnotes
    binary: launchnotes_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # GitLab plugin
  - id: plugin-gitlab
    main: ./plugins/gitlab
    binary: gitlab_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

  # Jira plugin
  - id: plugin-jira
    main: ./plugins/jira
    binary: jira_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    no_unique_dist_dir: true

archives:
  # Main CLI archive (without plugins)
  - id: main
    builds:
      - relicta
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other"
      order: 999

release:
  github:
    owner: relicta-tech
    name: relicta
  draft: false
  prerelease: auto
  mode: append
  # Publish individual plugin binaries as release assets
  extra_files:
    - glob: dist/github_*
    - glob: dist/gitlab_*
    - glob: dist/jira_*
    - glob: dist/npm_*
    - glob: dist/slack_*
    - glob: dist/discord_*
    - glob: dist/launchnotes_*
  header: |
    ## Relicta {{ .Tag }}

    AI-powered release management for modern software teams.
  footer: |
    **Full Changelog**: https://github.com/relicta-tech/relicta/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    ```bash
    # macOS (Apple Silicon)
    curl -L https://github.com/relicta-tech/relicta/releases/download/{{ .Tag }}/relicta_Darwin_arm64.tar.gz | tar xz

    # macOS (Intel)
    curl -L https://github.com/relicta-tech/relicta/releases/download/{{ .Tag }}/relicta_Darwin_x86_64.tar.gz | tar xz

    # Linux (amd64)
    curl -L https://github.com/relicta-tech/relicta/releases/download/{{ .Tag }}/relicta_Linux_x86_64.tar.gz | tar xz
    ```

brews:
  - name: relicta
    repository:
      owner: relicta-tech
      name: homebrew-tap
    homepage: https://github.com/relicta-tech/relicta
    description: AI-powered release management CLI
    license: MIT
    skip_upload: auto
    test: |
      system "#{bin}/relicta", "--version"
    install: |
      bin.install "relicta"
    caveats: |
      Plugins can be installed using:
        relicta plugin install <name>

nfpms:
  - id: packages
    package_name: relicta
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Felix Geelhaar
    homepage: https://github.com/relicta-tech/relicta
    maintainer: Felix Geelhaar <felix@geelhaar.dev>
    description: AI-powered release management CLI
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

# Docker builds disabled - build context issues in CI
# dockers:
#   - image_templates:
#       - "ghcr.io/relicta-tech/relicta:{{ .Tag }}"
#       - "ghcr.io/relicta-tech/relicta:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#       - "--label=org.opencontainers.image.description=AI-powered release management CLI"
#       - "--label=org.opencontainers.image.url=https://github.com/relicta-tech/relicta"
#       - "--label=org.opencontainers.image.source=https://github.com/relicta-tech/relicta"
#       - "--label=org.opencontainers.image.version={{ .Version }}"
#       - "--label=org.opencontainers.image.created={{ .Date }}"
#       - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#       - "--label=org.opencontainers.image.licenses=MIT"

# sboms disabled - syft not available in CI
# sboms:
#   - artifacts: archive

# signs disabled - cosign not available in CI
# signs:
#   - cmd: cosign
#     signature: "${artifact}.sig"
#     certificate: "${artifact}.pem"
#     args:
#       - "sign-blob"
#       - "--output-signature=${signature}"
#       - "--output-certificate=${certificate}"
#       - "${artifact}"
#       - "--yes"
#     artifacts: checksum
