# Plugin Release Workflow Template with Artifact Attestations
#
# This workflow template can be used by all Relicta plugins to:
# 1. Build multi-platform binaries
# 2. Generate SLSA provenance attestations
# 3. Create GitHub releases with verified artifacts
#
# To use: Copy to .github/workflows/release.yaml in your plugin repo
# Replace PLUGIN_NAME with your plugin name (e.g., github, slack, docker)

name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write      # Needed for OIDC token (Sigstore signing)
  attestations: write  # Needed for artifact attestations

env:
  PLUGIN_NAME: github  # CHANGE THIS to your plugin name

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            suffix: darwin_aarch64
          - goos: darwin
            goarch: amd64
            suffix: darwin_x86_64
          - goos: linux
            goarch: arm64
            suffix: linux_aarch64
          - goos: linux
            goarch: amd64
            suffix: linux_x86_64
          - goos: windows
            goarch: amd64
            suffix: windows_x86_64
            ext: .exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w -X main.Version=${{ github.ref_name }}" \
            -o ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}${{ matrix.ext }}

      - name: Package (Unix)
        if: matrix.goos != 'windows'
        run: |
          tar -czvf ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}.tar.gz \
            ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}

      - name: Package (Windows)
        if: matrix.goos == 'windows'
        run: |
          zip ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}.zip \
            ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}
          path: ${{ env.PLUGIN_NAME }}_${{ matrix.suffix }}.*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p release
          find dist -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec mv {} release/ \;

      - name: Generate checksums
        working-directory: release
        run: |
          sha256sum *.tar.gz *.zip > checksums.txt

      # Generate SLSA provenance attestations for all archives
      - name: Generate attestations
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            release/${{ env.PLUGIN_NAME }}_darwin_aarch64.tar.gz
            release/${{ env.PLUGIN_NAME }}_darwin_x86_64.tar.gz
            release/${{ env.PLUGIN_NAME }}_linux_aarch64.tar.gz
            release/${{ env.PLUGIN_NAME }}_linux_x86_64.tar.gz
            release/${{ env.PLUGIN_NAME }}_windows_x86_64.zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            release/*.tar.gz
            release/*.zip
            release/checksums.txt
