// Package plugin provides the public interface for ReleasePilot plugins.
// This file contains types that would normally be generated by protoc.
package plugin

import (
	"context"

	"google.golang.org/grpc"
)

// HookProto is the protobuf enum for hooks.
type HookProto int32

const (
	HookProto_HOOK_UNSPECIFIED  HookProto = 0
	HookProto_HOOK_PRE_INIT     HookProto = 1
	HookProto_HOOK_POST_INIT    HookProto = 2
	HookProto_HOOK_PRE_PLAN     HookProto = 3
	HookProto_HOOK_POST_PLAN    HookProto = 4
	HookProto_HOOK_PRE_VERSION  HookProto = 5
	HookProto_HOOK_POST_VERSION HookProto = 6
	HookProto_HOOK_PRE_NOTES    HookProto = 7
	HookProto_HOOK_POST_NOTES   HookProto = 8
	HookProto_HOOK_PRE_APPROVE  HookProto = 9
	HookProto_HOOK_POST_APPROVE HookProto = 10
	HookProto_HOOK_PRE_PUBLISH  HookProto = 11
	HookProto_HOOK_POST_PUBLISH HookProto = 12
	HookProto_HOOK_ON_SUCCESS   HookProto = 13
	HookProto_HOOK_ON_ERROR     HookProto = 14
)

// Empty is an empty message.
type Empty struct{}

// PluginInfo contains plugin metadata.
type PluginInfo struct {
	Name         string
	Version      string
	Description  string
	Author       string
	Hooks        []string
	ConfigSchema string
}

// ExecuteRequestProto is the protobuf request for Execute.
type ExecuteRequestProto struct {
	Hook    HookProto
	Config  string
	Context *ReleaseContextProto
	DryRun  bool
}

// ExecuteResponseProto is the protobuf response for Execute.
type ExecuteResponseProto struct {
	Success   bool
	Message   string
	Error     string
	Outputs   string
	Artifacts []*ArtifactProto
}

// ReleaseContextProto is the protobuf release context.
type ReleaseContextProto struct {
	Version         string
	PreviousVersion string
	TagName         string
	ReleaseType     string
	RepositoryUrl   string
	RepositoryOwner string
	RepositoryName  string
	Branch          string
	CommitSha       string
	Changelog       string
	ReleaseNotes    string
	Changes         *CategorizedChangesProto
	Environment     map[string]string
}

// CategorizedChangesProto is the protobuf categorized changes.
type CategorizedChangesProto struct {
	Features    []*ConventionalCommitProto
	Fixes       []*ConventionalCommitProto
	Breaking    []*ConventionalCommitProto
	Performance []*ConventionalCommitProto
	Refactor    []*ConventionalCommitProto
	Docs        []*ConventionalCommitProto
	Other       []*ConventionalCommitProto
}

// ConventionalCommitProto is the protobuf conventional commit.
type ConventionalCommitProto struct {
	Hash                string
	Type                string
	Scope               string
	Description         string
	Body                string
	Breaking            bool
	BreakingDescription string
	Issues              []string
	Author              string
	Date                string
}

// ArtifactProto is the protobuf artifact.
type ArtifactProto struct {
	Name     string
	Path     string
	Type     string
	Size     int64
	Checksum string
}

// ValidateRequestProto is the protobuf request for Validate.
type ValidateRequestProto struct {
	Config string
}

// ValidateResponseProto is the protobuf response for Validate.
type ValidateResponseProto struct {
	Valid  bool
	Errors []*ValidationErrorProto
}

// ValidationErrorProto is the protobuf validation error.
type ValidationErrorProto struct {
	Field   string
	Message string
	Code    string
}

// PluginClient is the client interface for the Plugin service.
type PluginClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Execute(ctx context.Context, in *ExecuteRequestProto, opts ...grpc.CallOption) (*ExecuteResponseProto, error)
	Validate(ctx context.Context, in *ValidateRequestProto, opts ...grpc.CallOption) (*ValidateResponseProto, error)
}

// PluginServer is the server interface for the Plugin service.
type PluginServer interface {
	GetInfo(context.Context, *Empty) (*PluginInfo, error)
	Execute(context.Context, *ExecuteRequestProto) (*ExecuteResponseProto, error)
	Validate(context.Context, *ValidateRequestProto) (*ValidateResponseProto, error)
}

// UnimplementedPluginServer is an empty implementation of PluginServer.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) GetInfo(context.Context, *Empty) (*PluginInfo, error) {
	return nil, nil
}

func (UnimplementedPluginServer) Execute(context.Context, *ExecuteRequestProto) (*ExecuteResponseProto, error) {
	return nil, nil
}

func (UnimplementedPluginServer) Validate(context.Context, *ValidateRequestProto) (*ValidateResponseProto, error) {
	return nil, nil
}

// pluginClient is the concrete implementation of PluginClient.
type pluginClient struct {
	cc grpc.ClientConnInterface
}

// NewPluginClient creates a new PluginClient.
func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc: cc}
}

func (c *pluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/plugin.Plugin/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Execute(ctx context.Context, in *ExecuteRequestProto, opts ...grpc.CallOption) (*ExecuteResponseProto, error) {
	out := new(ExecuteResponseProto)
	err := c.cc.Invoke(ctx, "/plugin.Plugin/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Validate(ctx context.Context, in *ValidateRequestProto, opts ...grpc.CallOption) (*ValidateResponseProto, error) {
	out := new(ValidateResponseProto)
	err := c.cc.Invoke(ctx, "/plugin.Plugin/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterPluginServer registers a PluginServer with a gRPC server.
func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Plugin_GetInfo_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Plugin_Execute_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Plugin_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

func _Plugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.Plugin/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.Plugin/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Execute(ctx, req.(*ExecuteRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.Plugin/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Validate(ctx, req.(*ValidateRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}
