package attribution

import (
	"regexp"
	"strconv"
	"strings"

	"github.com/relicta-tech/relicta/v4/internal/cgp"
)

// CommitInfo contains commit metadata for attribution detection.
type CommitInfo struct {
	Hash           string
	AuthorName     string
	AuthorEmail    string
	CommitterName  string
	CommitterEmail string
	Message        string
	Trailers       map[string]string
}

// DetectionResult contains the result of attribution detection.
type DetectionResult struct {
	// Actor is the detected actor.
	Actor cgp.Actor

	// Confidence is how confident we are in the detection (0.0-1.0).
	Confidence float64

	// Method describes how the attribution was detected.
	Method string

	// Evidence contains the data that led to this detection.
	Evidence map[string]string
}

// Detector detects which agent or human made changes.
type Detector struct {
	// AgentPatterns maps agent identifiers to their detection patterns.
	agentPatterns map[string]*AgentPattern

	// KnownAgentEmails maps email patterns to agent names.
	knownAgentEmails map[string]string

	// KnownCIEmails maps email patterns to CI system names.
	knownCIEmails map[string]string
}

// AgentPattern defines how to detect a specific agent.
type AgentPattern struct {
	// Name is the agent's display name.
	Name string

	// Model is the AI model name (if applicable).
	Model string

	// EmailPatterns are regex patterns to match author/committer emails.
	EmailPatterns []*regexp.Regexp

	// NamePatterns are regex patterns to match author/committer names.
	NamePatterns []*regexp.Regexp

	// TrailerKeys are git trailer keys that indicate this agent.
	TrailerKeys []string

	// MessagePatterns are regex patterns to match in commit messages.
	MessagePatterns []*regexp.Regexp

	// DefaultTrustLevel is the default trust level for this agent.
	DefaultTrustLevel cgp.TrustLevel
}

// NewDetector creates a new attribution detector with default patterns.
func NewDetector() *Detector {
	d := &Detector{
		agentPatterns:    make(map[string]*AgentPattern),
		knownAgentEmails: make(map[string]string),
		knownCIEmails:    make(map[string]string),
	}
	d.registerDefaultPatterns()
	return d
}

// registerDefaultPatterns sets up detection patterns for known agents and CI systems.
func (d *Detector) registerDefaultPatterns() {
	// Claude Code / Anthropic
	d.RegisterAgent(&AgentPattern{
		Name:  "Claude Code",
		Model: "claude",
		EmailPatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)claude@anthropic\.com`),
			regexp.MustCompile(`(?i).*\+claude@.*`),
		},
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)^claude$`),
			regexp.MustCompile(`(?i)claude\s*(code|ai)?`),
		},
		TrailerKeys: []string{"AI-Agent", "Agent", "Generated-By"},
		MessagePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)generated by claude`),
			regexp.MustCompile(`(?i)\[claude\]`),
		},
		DefaultTrustLevel: cgp.TrustLevelLimited,
	})

	// Cursor
	d.RegisterAgent(&AgentPattern{
		Name:  "Cursor",
		Model: "cursor",
		EmailPatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)cursor@.*`),
			regexp.MustCompile(`(?i).*\+cursor@.*`),
		},
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)^cursor$`),
			regexp.MustCompile(`(?i)cursor\s*ai`),
		},
		TrailerKeys: []string{"AI-Agent", "Agent"},
		MessagePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)generated by cursor`),
			regexp.MustCompile(`(?i)\[cursor\]`),
		},
		DefaultTrustLevel: cgp.TrustLevelLimited,
	})

	// GitHub Copilot
	d.RegisterAgent(&AgentPattern{
		Name:  "GitHub Copilot",
		Model: "copilot",
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)copilot`),
			regexp.MustCompile(`(?i)github\s*copilot`),
		},
		TrailerKeys: []string{"Co-authored-by"},
		MessagePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)co-authored-by:.*copilot`),
			regexp.MustCompile(`(?i)generated.*copilot`),
		},
		DefaultTrustLevel: cgp.TrustLevelLimited,
	})

	// Aider
	d.RegisterAgent(&AgentPattern{
		Name:  "Aider",
		Model: "aider",
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)^aider$`),
		},
		TrailerKeys: []string{"Aider"},
		MessagePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)aider:`),
			regexp.MustCompile(`(?i)^aider\s`),
		},
		DefaultTrustLevel: cgp.TrustLevelLimited,
	})

	// Codeium / Windsurf
	d.RegisterAgent(&AgentPattern{
		Name:  "Windsurf",
		Model: "windsurf",
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)windsurf`),
			regexp.MustCompile(`(?i)codeium`),
		},
		MessagePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)windsurf`),
			regexp.MustCompile(`(?i)codeium`),
		},
		DefaultTrustLevel: cgp.TrustLevelLimited,
	})

	// Common CI system emails
	d.knownCIEmails = map[string]string{
		"noreply@github.com":                           "github-actions",
		"actions@github.com":                           "github-actions",
		"github-actions@github.com":                    "github-actions",
		"github-actions[bot]@users.noreply.github.com": "github-actions",
		"gitlab@gitlab.com":                            "gitlab-ci",
		"noreply@gitlab.com":                           "gitlab-ci",
		"jenkins@":                                     "jenkins",
		"circleci@":                                    "circleci",
		"travis@":                                      "travis-ci",
		"drone@":                                       "drone",
	}
}

// RegisterAgent adds a new agent pattern.
func (d *Detector) RegisterAgent(pattern *AgentPattern) {
	d.agentPatterns[pattern.Name] = pattern
}

// Detect identifies the actor from commit information.
func (d *Detector) Detect(commit *CommitInfo) *DetectionResult {
	// Check for explicit agent trailers first (highest confidence)
	if result := d.detectFromTrailers(commit); result != nil {
		return result
	}

	// Check for known agent patterns
	if result := d.detectAgent(commit); result != nil {
		return result
	}

	// Check for CI systems
	if result := d.detectCI(commit); result != nil {
		return result
	}

	// Default to human
	return d.detectHuman(commit)
}

// detectFromTrailers checks git trailers for agent attribution.
func (d *Detector) detectFromTrailers(commit *CommitInfo) *DetectionResult {
	for key, value := range commit.Trailers {
		lowerKey := strings.ToLower(key)

		// Check for AI-Agent trailer
		if lowerKey == "ai-agent" || lowerKey == "agent" || lowerKey == "generated-by" {
			// Try to match to known agent
			for _, pattern := range d.agentPatterns {
				for _, np := range pattern.NamePatterns {
					if np.MatchString(value) {
						return &DetectionResult{
							Actor: cgp.NewAgentActor(
								strings.ToLower(pattern.Name),
								pattern.Name,
								pattern.Model,
							),
							Confidence: 0.95,
							Method:     "trailer",
							Evidence: map[string]string{
								"trailer_key":   key,
								"trailer_value": value,
							},
						}
					}
				}
			}

			// Unknown agent from trailer
			return &DetectionResult{
				Actor: cgp.NewAgentActor(
					strings.ToLower(strings.ReplaceAll(value, " ", "-")),
					value,
					"",
				),
				Confidence: 0.85,
				Method:     "trailer",
				Evidence: map[string]string{
					"trailer_key":   key,
					"trailer_value": value,
				},
			}
		}
	}
	return nil
}

// detectAgent checks for known agent patterns.
func (d *Detector) detectAgent(commit *CommitInfo) *DetectionResult {
	for _, pattern := range d.agentPatterns {
		// Check email patterns
		for _, ep := range pattern.EmailPatterns {
			if ep.MatchString(commit.AuthorEmail) || ep.MatchString(commit.CommitterEmail) {
				return &DetectionResult{
					Actor: cgp.NewAgentActor(
						strings.ToLower(pattern.Name),
						pattern.Name,
						pattern.Model,
					),
					Confidence: 0.9,
					Method:     "email_pattern",
					Evidence: map[string]string{
						"author_email":    commit.AuthorEmail,
						"committer_email": commit.CommitterEmail,
						"pattern":         pattern.Name,
					},
				}
			}
		}

		// Check name patterns
		for _, np := range pattern.NamePatterns {
			if np.MatchString(commit.AuthorName) || np.MatchString(commit.CommitterName) {
				return &DetectionResult{
					Actor: cgp.NewAgentActor(
						strings.ToLower(pattern.Name),
						pattern.Name,
						pattern.Model,
					),
					Confidence: 0.8,
					Method:     "name_pattern",
					Evidence: map[string]string{
						"author_name":    commit.AuthorName,
						"committer_name": commit.CommitterName,
						"pattern":        pattern.Name,
					},
				}
			}
		}

		// Check message patterns
		for _, mp := range pattern.MessagePatterns {
			if mp.MatchString(commit.Message) {
				return &DetectionResult{
					Actor: cgp.NewAgentActor(
						strings.ToLower(pattern.Name),
						pattern.Name,
						pattern.Model,
					),
					Confidence: 0.7,
					Method:     "message_pattern",
					Evidence: map[string]string{
						"message": commit.Message[:min(100, len(commit.Message))],
						"pattern": pattern.Name,
					},
				}
			}
		}
	}
	return nil
}

// detectCI checks for CI system patterns.
func (d *Detector) detectCI(commit *CommitInfo) *DetectionResult {
	emailToCheck := strings.ToLower(commit.AuthorEmail)

	for pattern, ciName := range d.knownCIEmails {
		if strings.Contains(emailToCheck, strings.ToLower(pattern)) {
			return &DetectionResult{
				Actor:      cgp.NewCIActor(ciName, "", ""),
				Confidence: 0.9,
				Method:     "ci_email",
				Evidence: map[string]string{
					"author_email": commit.AuthorEmail,
					"ci_system":    ciName,
				},
			}
		}
	}

	// Check for bot indicators in name
	lowerName := strings.ToLower(commit.AuthorName)
	if strings.Contains(lowerName, "[bot]") || strings.Contains(lowerName, "-bot") {
		ciName := strings.TrimSuffix(strings.TrimSuffix(lowerName, "[bot]"), "-bot")
		return &DetectionResult{
			Actor:      cgp.NewCIActor(ciName, "", ""),
			Confidence: 0.85,
			Method:     "bot_name",
			Evidence: map[string]string{
				"author_name": commit.AuthorName,
			},
		}
	}

	return nil
}

// detectHuman returns a human actor based on commit info.
func (d *Detector) detectHuman(commit *CommitInfo) *DetectionResult {
	return &DetectionResult{
		Actor:      cgp.NewHumanActor(commit.AuthorEmail, commit.AuthorName),
		Confidence: 0.95,
		Method:     "default_human",
		Evidence: map[string]string{
			"author_email": commit.AuthorEmail,
			"author_name":  commit.AuthorName,
		},
	}
}

// DetectMultiple detects attribution for multiple commits.
// Returns the dominant actor (most common) with aggregated confidence.
func (d *Detector) DetectMultiple(commits []*CommitInfo) *DetectionResult {
	if len(commits) == 0 {
		return nil
	}

	if len(commits) == 1 {
		return d.Detect(commits[0])
	}

	// Count actors by ID
	actorCounts := make(map[string]int)
	actorResults := make(map[string]*DetectionResult)

	for _, commit := range commits {
		result := d.Detect(commit)
		actorCounts[result.Actor.ID]++
		actorResults[result.Actor.ID] = result
	}

	// Find dominant actor
	var dominantID string
	maxCount := 0
	for id, count := range actorCounts {
		if count > maxCount {
			maxCount = count
			dominantID = id
		}
	}

	result := actorResults[dominantID]

	// Adjust confidence based on consistency
	consistency := float64(maxCount) / float64(len(commits))
	result.Confidence = result.Confidence * consistency

	result.Evidence["commit_count"] = strconv.Itoa(len(commits))
	result.Evidence["actor_count"] = strconv.Itoa(maxCount)

	return result
}
