package attribution

import (
	"regexp"
	"testing"

	"github.com/relicta-tech/relicta/v4/internal/cgp"
)

func TestDetector_DetectHuman(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "John Doe",
		AuthorEmail: "john@example.com",
		Message:     "feat: add new feature",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindHuman {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindHuman)
	}
	if result.Confidence < 0.9 {
		t.Errorf("Confidence = %f, want >= 0.9", result.Confidence)
	}
	if result.Method != "default_human" {
		t.Errorf("Method = %s, want default_human", result.Method)
	}
}

func TestDetector_DetectClaudeByEmail(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Developer",
		AuthorEmail: "developer+claude@example.com",
		Message:     "refactor: improve performance",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
	if result.Confidence < 0.8 {
		t.Errorf("Confidence = %f, want >= 0.8", result.Confidence)
	}
}

func TestDetector_DetectClaudeByName(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Claude",
		AuthorEmail: "user@example.com",
		Message:     "fix: resolve bug",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
	if result.Method != "name_pattern" {
		t.Errorf("Method = %s, want name_pattern", result.Method)
	}
}

func TestDetector_DetectByTrailer(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Developer",
		AuthorEmail: "dev@example.com",
		Message:     "feat: add feature\n\nAI-Agent: Claude",
		Trailers: map[string]string{
			"AI-Agent": "Claude",
		},
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
	if result.Method != "trailer" {
		t.Errorf("Method = %s, want trailer", result.Method)
	}
	if result.Confidence < 0.9 {
		t.Errorf("Confidence = %f, want >= 0.9", result.Confidence)
	}
}

func TestDetector_DetectUnknownAgentByTrailer(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Developer",
		AuthorEmail: "dev@example.com",
		Message:     "feat: add feature",
		Trailers: map[string]string{
			"Generated-By": "CustomAI v2",
		},
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
	if result.Method != "trailer" {
		t.Errorf("Method = %s, want trailer", result.Method)
	}
	// Unknown agent has lower confidence
	if result.Confidence >= 0.9 {
		t.Errorf("Unknown agent confidence = %f, should be < 0.9", result.Confidence)
	}
}

func TestDetector_DetectGitHubActions(t *testing.T) {
	d := NewDetector()

	tests := []struct {
		email string
	}{
		{"noreply@github.com"},
		{"actions@github.com"},
		{"github-actions@github.com"},
		{"github-actions[bot]@users.noreply.github.com"},
	}

	for _, tt := range tests {
		commit := &CommitInfo{
			Hash:        "abc123",
			AuthorName:  "GitHub Actions",
			AuthorEmail: tt.email,
			Message:     "chore: automated update",
		}

		result := d.Detect(commit)

		if result.Actor.Kind != cgp.ActorKindCI {
			t.Errorf("For email %s: Kind = %s, want %s", tt.email, result.Actor.Kind, cgp.ActorKindCI)
		}
	}
}

func TestDetector_DetectBotByName(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "dependabot[bot]",
		AuthorEmail: "dependabot@users.noreply.github.com",
		Message:     "chore(deps): bump lodash",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindCI {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindCI)
	}
	if result.Method != "bot_name" {
		t.Errorf("Method = %s, want bot_name", result.Method)
	}
}

func TestDetector_DetectByMessagePattern(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Developer",
		AuthorEmail: "dev@example.com",
		Message:     "feat: add login page\n\nGenerated by Claude based on user requirements",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
	if result.Method != "message_pattern" {
		t.Errorf("Method = %s, want message_pattern", result.Method)
	}
}

func TestDetector_DetectCursor(t *testing.T) {
	d := NewDetector()

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "Cursor AI",
		AuthorEmail: "dev@example.com",
		Message:     "refactor: optimize queries",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
}

func TestDetector_RegisterCustomAgent(t *testing.T) {
	d := NewDetector()

	// Register a custom agent pattern
	d.RegisterAgent(&AgentPattern{
		Name:  "CustomBot",
		Model: "custom-v1",
		NamePatterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)custombot`),
		},
		DefaultTrustLevel: cgp.TrustLevelTrusted,
	})

	commit := &CommitInfo{
		Hash:        "abc123",
		AuthorName:  "CustomBot",
		AuthorEmail: "bot@internal.com",
		Message:     "automated update",
	}

	result := d.Detect(commit)

	if result.Actor.Kind != cgp.ActorKindAgent {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindAgent)
	}
}

func TestDetector_DetectMultiple(t *testing.T) {
	d := NewDetector()

	commits := []*CommitInfo{
		{Hash: "1", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: a"},
		{Hash: "2", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: b"},
		{Hash: "3", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: c"},
	}

	result := d.DetectMultiple(commits)

	if result.Actor.Kind != cgp.ActorKindHuman {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindHuman)
	}
	// High confidence for consistent authorship
	if result.Confidence < 0.9 {
		t.Errorf("Confidence = %f, want >= 0.9 for consistent authorship", result.Confidence)
	}
}

func TestDetector_DetectMultipleMixedAuthors(t *testing.T) {
	d := NewDetector()

	commits := []*CommitInfo{
		{Hash: "1", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: a"},
		{Hash: "2", AuthorName: "Jane", AuthorEmail: "jane@example.com", Message: "feat: b"},
		{Hash: "3", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: c"},
	}

	result := d.DetectMultiple(commits)

	// Should still detect dominant author
	if result.Actor.Kind != cgp.ActorKindHuman {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindHuman)
	}
	// Lower confidence for mixed authorship
	if result.Confidence > 0.8 {
		t.Errorf("Confidence = %f, should be lower for mixed authorship", result.Confidence)
	}
}

func TestDetector_DetectMultipleEmpty(t *testing.T) {
	d := NewDetector()

	result := d.DetectMultiple([]*CommitInfo{})
	if result != nil {
		t.Error("DetectMultiple should return nil for empty commits")
	}
}

func TestDetector_DetectMultipleSingle(t *testing.T) {
	d := NewDetector()

	commits := []*CommitInfo{
		{Hash: "1", AuthorName: "John", AuthorEmail: "john@example.com", Message: "feat: a"},
	}

	result := d.DetectMultiple(commits)
	if result == nil {
		t.Fatal("DetectMultiple should not return nil for single commit")
	}
	if result.Actor.Kind != cgp.ActorKindHuman {
		t.Errorf("Kind = %s, want %s", result.Actor.Kind, cgp.ActorKindHuman)
	}
}
