package compliance

import (
	"fmt"
	"strings"
)

// RenderMarkdown renders a report as a Markdown document.
func RenderMarkdown(report *Report) string {
	var b strings.Builder

	writeHeader(&b, report)

	switch report.Type {
	case ReportDORA:
		writeDORA(&b, report.DORA)
	case ReportSOC2:
		writeSOC2(&b, report.SOC2)
	case ReportSummary:
		writeSummary(&b, report.Summary)
	}

	writeFooter(&b, report)

	return b.String()
}

func writeHeader(b *strings.Builder, r *Report) {
	title := ""
	switch r.Type {
	case ReportDORA:
		title = "DORA Metrics Report"
	case ReportSOC2:
		title = "SOC 2 Change Management Evidence"
	case ReportSummary:
		title = "Governance Summary Report"
	}

	fmt.Fprintf(b, "# %s\n\n", title)
	fmt.Fprintf(b, "**Period:** %s\n\n", r.Period.Label)
	if r.Repository != "" {
		fmt.Fprintf(b, "**Repository:** %s\n\n", r.Repository)
	}
	fmt.Fprintf(b, "**Generated:** %s\n\n", r.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintln(b, "---")
	fmt.Fprintln(b)
}

func writeFooter(b *strings.Builder, r *Report) {
	fmt.Fprintln(b, "---")
	fmt.Fprintln(b)
	fmt.Fprintf(b, "*Report generated by Relicta Compliance Reporter at %s*\n", r.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))
}

func writeDORA(b *strings.Builder, r *DORAReport) {
	if r == nil {
		fmt.Fprintln(b, "No DORA data available.")
		fmt.Fprintln(b)
		return
	}

	fmt.Fprintf(b, "**Overall Classification: %s**\n\n", strings.ToUpper(r.Classification))

	// Deployment Frequency
	fmt.Fprintln(b, "## Deployment Frequency")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Metric | Value |")
	fmt.Fprintln(b, "|--------|-------|")
	fmt.Fprintf(b, "| Total Deployments | %d |\n", r.DeploymentFrequency.TotalDeployments)
	fmt.Fprintf(b, "| Per Day | %.2f |\n", r.DeploymentFrequency.PerDay)
	fmt.Fprintf(b, "| Per Week | %.2f |\n", r.DeploymentFrequency.PerWeek)
	fmt.Fprintf(b, "| Classification | %s |\n", r.DeploymentFrequency.Classification)
	fmt.Fprintln(b)

	// Lead Time
	fmt.Fprintln(b, "## Lead Time for Changes")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Metric | Value |")
	fmt.Fprintln(b, "|--------|-------|")
	fmt.Fprintf(b, "| Average | %.1f hours |\n", r.LeadTimeForChanges.AverageHours)
	fmt.Fprintf(b, "| Median | %.1f hours |\n", r.LeadTimeForChanges.MedianHours)
	fmt.Fprintf(b, "| P95 | %.1f hours |\n", r.LeadTimeForChanges.P95Hours)
	fmt.Fprintf(b, "| Classification | %s |\n", r.LeadTimeForChanges.Classification)
	fmt.Fprintln(b)

	// MTTR
	fmt.Fprintln(b, "## Mean Time to Recovery (MTTR)")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Metric | Value |")
	fmt.Fprintln(b, "|--------|-------|")
	fmt.Fprintf(b, "| Average | %.1f hours |\n", r.MTTR.AverageHours)
	fmt.Fprintf(b, "| Median | %.1f hours |\n", r.MTTR.MedianHours)
	fmt.Fprintf(b, "| Total Incidents | %d |\n", r.MTTR.TotalIncidents)
	fmt.Fprintf(b, "| Resolved | %d |\n", r.MTTR.ResolvedCount)
	fmt.Fprintf(b, "| Classification | %s |\n", r.MTTR.Classification)
	fmt.Fprintln(b)

	// Change Failure Rate
	fmt.Fprintln(b, "## Change Failure Rate")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Metric | Value |")
	fmt.Fprintln(b, "|--------|-------|")
	fmt.Fprintf(b, "| Total Changes | %d |\n", r.ChangeFailureRate.TotalChanges)
	fmt.Fprintf(b, "| Failed Changes | %d |\n", r.ChangeFailureRate.FailedChanges)
	fmt.Fprintf(b, "| Failure Rate | %.1f%% |\n", r.ChangeFailureRate.Rate*100)
	fmt.Fprintf(b, "| Classification | %s |\n", r.ChangeFailureRate.Classification)
	fmt.Fprintln(b)
}

func writeSOC2(b *strings.Builder, r *SOC2Report) {
	if r == nil {
		fmt.Fprintln(b, "No SOC 2 data available.")
		fmt.Fprintln(b)
		return
	}

	// Change Log
	fmt.Fprintln(b, "## Change Request Log")
	fmt.Fprintln(b)
	if len(r.ChangeLog) == 0 {
		fmt.Fprintln(b, "No changes recorded in this period.")
	} else {
		fmt.Fprintln(b, "| ID | Version | Date | Actor | Risk Score | Decision | Outcome |")
		fmt.Fprintln(b, "|----|---------|------|-------|------------|----------|---------|")
		for _, c := range r.ChangeLog {
			fmt.Fprintf(b, "| %s | %s | %s | %s (%s) | %.2f | %s | %s |\n",
				c.ID, c.Version, c.Date.Format("2006-01-02"),
				c.Actor, c.ActorKind, c.RiskScore, c.Decision, c.Outcome)
		}
	}
	fmt.Fprintln(b)

	// Approval Evidence
	fmt.Fprintln(b, "## Approval Evidence")
	fmt.Fprintln(b)
	if len(r.ApprovalEvidence) == 0 {
		fmt.Fprintln(b, "No approval records in this period.")
	} else {
		fmt.Fprintln(b, "| Release | Version | Decision | Risk Score | Date |")
		fmt.Fprintln(b, "|---------|---------|----------|------------|------|")
		for _, a := range r.ApprovalEvidence {
			fmt.Fprintf(b, "| %s | %s | %s | %.2f | %s |\n",
				a.ReleaseID, a.Version, a.DecisionType, a.RiskScore,
				a.ApprovedAt.Format("2006-01-02 15:04"))
		}
	}
	fmt.Fprintln(b)

	// Risk Assessments
	fmt.Fprintln(b, "## Risk Assessment Evidence")
	fmt.Fprintln(b)
	if len(r.RiskAssessments) == 0 {
		fmt.Fprintln(b, "No risk assessments in this period.")
	} else {
		for _, ra := range r.RiskAssessments {
			fmt.Fprintf(b, "### %s (v%s) - Risk: %s (%.2f)\n\n", ra.ReleaseID, ra.Version, ra.RiskLevel, ra.RiskScore)
			if len(ra.RiskFactors) > 0 {
				fmt.Fprintln(b, "| Category | Severity | Score | Description |")
				fmt.Fprintln(b, "|----------|----------|-------|-------------|")
				for _, rf := range ra.RiskFactors {
					fmt.Fprintf(b, "| %s | %s | %.2f | %s |\n",
						rf.Category, rf.Severity, rf.Score, rf.Description)
				}
			}
			fmt.Fprintln(b)
		}
	}

	// Incident Response
	fmt.Fprintln(b, "## Incident Response")
	fmt.Fprintln(b)
	if len(r.IncidentResponse) == 0 {
		fmt.Fprintln(b, "No incidents recorded in this period.")
	} else {
		fmt.Fprintln(b, "| Incident | Release | Version | Type | Severity | Detected | Resolution Time |")
		fmt.Fprintln(b, "|----------|---------|---------|------|----------|----------|-----------------|")
		for _, inc := range r.IncidentResponse {
			resolution := "unresolved"
			if inc.TimeToResolve > 0 {
				resolution = inc.TimeToResolve.String()
			}
			fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s | %s |\n",
				inc.IncidentID, inc.ReleaseID, inc.Version,
				inc.Type, inc.Severity,
				inc.DetectedAt.Format("2006-01-02 15:04"), resolution)
		}
	}
	fmt.Fprintln(b)

	// Policy Compliance
	fmt.Fprintln(b, "## Policy Compliance")
	fmt.Fprintln(b)
	if len(r.PolicyCompliance) == 0 {
		fmt.Fprintln(b, "No policy evaluations in this period.")
	} else {
		fmt.Fprintln(b, "| Release | Version | Decision | Risk Score | Rationale |")
		fmt.Fprintln(b, "|---------|---------|----------|------------|-----------|")
		for _, pc := range r.PolicyCompliance {
			rationale := strings.Join(pc.Rationale, "; ")
			if len(rationale) > 80 {
				rationale = rationale[:77] + "..."
			}
			fmt.Fprintf(b, "| %s | %s | %s | %.2f | %s |\n",
				pc.ReleaseID, pc.Version, pc.Decision, pc.RiskScore, rationale)
		}
	}
	fmt.Fprintln(b)
}

func writeSummary(b *strings.Builder, r *SummaryReport) {
	if r == nil {
		fmt.Fprintln(b, "No summary data available.")
		fmt.Fprintln(b)
		return
	}

	fmt.Fprintf(b, "## Overview\n\n")
	fmt.Fprintf(b, "**Total Releases:** %d\n\n", r.TotalReleases)

	// Risk Distribution
	fmt.Fprintln(b, "## Risk Score Distribution")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Level | Count |")
	fmt.Fprintln(b, "|-------|-------|")
	fmt.Fprintf(b, "| Low (< 0.4) | %d |\n", r.RiskDistribution.Low)
	fmt.Fprintf(b, "| Medium (0.4-0.6) | %d |\n", r.RiskDistribution.Medium)
	fmt.Fprintf(b, "| High (0.6-0.8) | %d |\n", r.RiskDistribution.High)
	fmt.Fprintf(b, "| Critical (>= 0.8) | %d |\n", r.RiskDistribution.Critical)
	fmt.Fprintln(b)

	// Approval Breakdown
	fmt.Fprintln(b, "## Approval Breakdown")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Type | Count |")
	fmt.Fprintln(b, "|------|-------|")
	fmt.Fprintf(b, "| Auto-Approved | %d |\n", r.ApprovalBreakdown.AutoApproved)
	fmt.Fprintf(b, "| Human-Approved | %d |\n", r.ApprovalBreakdown.HumanApproved)
	fmt.Fprintf(b, "| Rejected | %d |\n", r.ApprovalBreakdown.Rejected)
	fmt.Fprintln(b)

	// Top Risk Factors
	if len(r.TopRiskFactors) > 0 {
		fmt.Fprintln(b, "## Top Risk Factors")
		fmt.Fprintln(b)
		fmt.Fprintln(b, "| Category | Occurrences | Avg Score |")
		fmt.Fprintln(b, "|----------|-------------|-----------|")
		for _, rf := range r.TopRiskFactors {
			fmt.Fprintf(b, "| %s | %d | %.2f |\n", rf.Category, rf.Count, rf.AvgScore)
		}
		fmt.Fprintln(b)
	}

	// Actor Activity
	if len(r.ActorActivity) > 0 {
		fmt.Fprintln(b, "## Actor Activity")
		fmt.Fprintln(b)
		fmt.Fprintln(b, "| Actor | Kind | Releases | Success Rate | Avg Risk |")
		fmt.Fprintln(b, "|-------|------|----------|--------------|----------|")
		for _, a := range r.ActorActivity {
			fmt.Fprintf(b, "| %s | %s | %d | %.0f%% | %.2f |\n",
				a.ActorID, a.ActorKind, a.ReleaseCount,
				a.SuccessRate*100, a.AvgRiskScore)
		}
		fmt.Fprintln(b)
	}

	// Incident Summary
	fmt.Fprintln(b, "## Incident Summary")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Metric | Value |")
	fmt.Fprintln(b, "|--------|-------|")
	fmt.Fprintf(b, "| Total Incidents | %d |\n", r.IncidentSummary.TotalIncidents)
	fmt.Fprintf(b, "| Avg Resolution Time | %.1f hours |\n", r.IncidentSummary.AvgResolutionHrs)
	fmt.Fprintf(b, "| Incidents per Release | %.2f |\n", r.IncidentSummary.CorrelationRate)
	fmt.Fprintln(b)
}
