// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hook represents a hook type in the release workflow.
type Hook int32

const (
	Hook_HOOK_UNSPECIFIED  Hook = 0
	Hook_HOOK_PRE_INIT     Hook = 1
	Hook_HOOK_POST_INIT    Hook = 2
	Hook_HOOK_PRE_PLAN     Hook = 3
	Hook_HOOK_POST_PLAN    Hook = 4
	Hook_HOOK_PRE_VERSION  Hook = 5
	Hook_HOOK_POST_VERSION Hook = 6
	Hook_HOOK_PRE_NOTES    Hook = 7
	Hook_HOOK_POST_NOTES   Hook = 8
	Hook_HOOK_PRE_APPROVE  Hook = 9
	Hook_HOOK_POST_APPROVE Hook = 10
	Hook_HOOK_PRE_PUBLISH  Hook = 11
	Hook_HOOK_POST_PUBLISH Hook = 12
	Hook_HOOK_ON_SUCCESS   Hook = 13
	Hook_HOOK_ON_ERROR     Hook = 14
)

// Enum value maps for Hook.
var (
	Hook_name = map[int32]string{
		0:  "HOOK_UNSPECIFIED",
		1:  "HOOK_PRE_INIT",
		2:  "HOOK_POST_INIT",
		3:  "HOOK_PRE_PLAN",
		4:  "HOOK_POST_PLAN",
		5:  "HOOK_PRE_VERSION",
		6:  "HOOK_POST_VERSION",
		7:  "HOOK_PRE_NOTES",
		8:  "HOOK_POST_NOTES",
		9:  "HOOK_PRE_APPROVE",
		10: "HOOK_POST_APPROVE",
		11: "HOOK_PRE_PUBLISH",
		12: "HOOK_POST_PUBLISH",
		13: "HOOK_ON_SUCCESS",
		14: "HOOK_ON_ERROR",
	}
	Hook_value = map[string]int32{
		"HOOK_UNSPECIFIED":  0,
		"HOOK_PRE_INIT":     1,
		"HOOK_POST_INIT":    2,
		"HOOK_PRE_PLAN":     3,
		"HOOK_POST_PLAN":    4,
		"HOOK_PRE_VERSION":  5,
		"HOOK_POST_VERSION": 6,
		"HOOK_PRE_NOTES":    7,
		"HOOK_POST_NOTES":   8,
		"HOOK_PRE_APPROVE":  9,
		"HOOK_POST_APPROVE": 10,
		"HOOK_PRE_PUBLISH":  11,
		"HOOK_POST_PUBLISH": 12,
		"HOOK_ON_SUCCESS":   13,
		"HOOK_ON_ERROR":     14,
	}
)

func (x Hook) Enum() *Hook {
	p := new(Hook)
	*p = x
	return p
}

func (x Hook) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_plugin_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (Hook) Type() protoreflect.EnumType {
	return &file_internal_plugin_proto_plugin_proto_enumTypes[0]
}

func (x Hook) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook.Descriptor instead.
func (Hook) EnumDescriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

// Empty is an empty message for requests that don't need input.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

// PluginInfo contains metadata about the plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// description is a short description of the plugin.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// author is the plugin author.
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// hooks lists the hooks this plugin supports.
	Hooks []string `protobuf:"bytes,5,rep,name=hooks,proto3" json:"hooks,omitempty"`
	// config_schema is a JSON schema for the plugin configuration.
	ConfigSchema  string `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginInfo) GetConfigSchema() string {
	if x != nil {
		return x.ConfigSchema
	}
	return ""
}

// ExecuteRequest is the request for executing a plugin hook.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hook is the hook being executed.
	Hook Hook `protobuf:"varint,1,opt,name=hook,proto3,enum=relicta.Hook" json:"hook,omitempty"`
	// config is the plugin-specific configuration as JSON.
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// context contains the release context.
	Context *ReleaseContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// dry_run indicates if this is a dry run.
	DryRun        bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetHook() Hook {
	if x != nil {
		return x.Hook
	}
	return Hook_HOOK_UNSPECIFIED
}

func (x *ExecuteRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ExecuteRequest) GetContext() *ReleaseContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// ExecuteResponse is the response from plugin execution.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates if the execution was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message is an optional message about the execution.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// error is the error message if execution failed.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// outputs contains any outputs from the plugin as JSON.
	Outputs string `protobuf:"bytes,4,opt,name=outputs,proto3" json:"outputs,omitempty"`
	// artifacts lists any artifacts created by the plugin.
	Artifacts     []*Artifact `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetOutputs() string {
	if x != nil {
		return x.Outputs
	}
	return ""
}

func (x *ExecuteResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// ReleaseContext contains information about the current release.
type ReleaseContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the release version (e.g., "1.2.3").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// previous_version is the previous release version.
	PreviousVersion string `protobuf:"bytes,2,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	// tag_name is the full tag name (e.g., "v1.2.3").
	TagName string `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	// release_type is the type of release (major, minor, patch).
	ReleaseType string `protobuf:"bytes,4,opt,name=release_type,json=releaseType,proto3" json:"release_type,omitempty"`
	// repository_url is the repository URL.
	RepositoryUrl string `protobuf:"bytes,5,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	// repository_owner is the repository owner.
	RepositoryOwner string `protobuf:"bytes,6,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	// repository_name is the repository name.
	RepositoryName string `protobuf:"bytes,7,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	// branch is the branch being released from.
	Branch string `protobuf:"bytes,8,opt,name=branch,proto3" json:"branch,omitempty"`
	// commit_sha is the HEAD commit SHA.
	CommitSha string `protobuf:"bytes,9,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	// changelog is the generated changelog content.
	Changelog string `protobuf:"bytes,10,opt,name=changelog,proto3" json:"changelog,omitempty"`
	// release_notes is the generated release notes.
	ReleaseNotes string `protobuf:"bytes,11,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	// changes contains the categorized changes.
	Changes *CategorizedChanges `protobuf:"bytes,12,opt,name=changes,proto3" json:"changes,omitempty"`
	// environment contains environment variables (filtered for security).
	Environment   map[string]string `protobuf:"bytes,13,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseContext) Reset() {
	*x = ReleaseContext{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseContext) ProtoMessage() {}

func (x *ReleaseContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseContext.ProtoReflect.Descriptor instead.
func (*ReleaseContext) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseContext) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReleaseContext) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *ReleaseContext) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ReleaseContext) GetReleaseType() string {
	if x != nil {
		return x.ReleaseType
	}
	return ""
}

func (x *ReleaseContext) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *ReleaseContext) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *ReleaseContext) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *ReleaseContext) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ReleaseContext) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ReleaseContext) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *ReleaseContext) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *ReleaseContext) GetChanges() *CategorizedChanges {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ReleaseContext) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

// CategorizedChanges contains commits grouped by category.
type CategorizedChanges struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// features lists feature commits.
	Features []*ConventionalCommit `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	// fixes lists bug fix commits.
	Fixes []*ConventionalCommit `protobuf:"bytes,2,rep,name=fixes,proto3" json:"fixes,omitempty"`
	// breaking lists breaking change commits.
	Breaking []*ConventionalCommit `protobuf:"bytes,3,rep,name=breaking,proto3" json:"breaking,omitempty"`
	// performance lists performance improvement commits.
	Performance []*ConventionalCommit `protobuf:"bytes,4,rep,name=performance,proto3" json:"performance,omitempty"`
	// refactor lists refactoring commits.
	Refactor []*ConventionalCommit `protobuf:"bytes,5,rep,name=refactor,proto3" json:"refactor,omitempty"`
	// docs lists documentation commits.
	Docs []*ConventionalCommit `protobuf:"bytes,6,rep,name=docs,proto3" json:"docs,omitempty"`
	// other lists other commits.
	Other         []*ConventionalCommit `protobuf:"bytes,7,rep,name=other,proto3" json:"other,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorizedChanges) Reset() {
	*x = CategorizedChanges{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizedChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizedChanges) ProtoMessage() {}

func (x *CategorizedChanges) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizedChanges.ProtoReflect.Descriptor instead.
func (*CategorizedChanges) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CategorizedChanges) GetFeatures() []*ConventionalCommit {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *CategorizedChanges) GetFixes() []*ConventionalCommit {
	if x != nil {
		return x.Fixes
	}
	return nil
}

func (x *CategorizedChanges) GetBreaking() []*ConventionalCommit {
	if x != nil {
		return x.Breaking
	}
	return nil
}

func (x *CategorizedChanges) GetPerformance() []*ConventionalCommit {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *CategorizedChanges) GetRefactor() []*ConventionalCommit {
	if x != nil {
		return x.Refactor
	}
	return nil
}

func (x *CategorizedChanges) GetDocs() []*ConventionalCommit {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *CategorizedChanges) GetOther() []*ConventionalCommit {
	if x != nil {
		return x.Other
	}
	return nil
}

// ConventionalCommit represents a parsed conventional commit.
type ConventionalCommit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash is the commit hash.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// type is the commit type (feat, fix, etc.).
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// scope is the optional scope.
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// description is the commit description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// body is the commit body.
	Body string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// breaking indicates if this is a breaking change.
	Breaking bool `protobuf:"varint,6,opt,name=breaking,proto3" json:"breaking,omitempty"`
	// breaking_description is the breaking change description.
	BreakingDescription string `protobuf:"bytes,7,opt,name=breaking_description,json=breakingDescription,proto3" json:"breaking_description,omitempty"`
	// issues lists referenced issues.
	Issues []string `protobuf:"bytes,8,rep,name=issues,proto3" json:"issues,omitempty"`
	// author is the commit author.
	Author string `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	// date is the commit date.
	Date          string `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConventionalCommit) Reset() {
	*x = ConventionalCommit{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConventionalCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConventionalCommit) ProtoMessage() {}

func (x *ConventionalCommit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConventionalCommit.ProtoReflect.Descriptor instead.
func (*ConventionalCommit) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConventionalCommit) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ConventionalCommit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConventionalCommit) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConventionalCommit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConventionalCommit) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ConventionalCommit) GetBreaking() bool {
	if x != nil {
		return x.Breaking
	}
	return false
}

func (x *ConventionalCommit) GetBreakingDescription() string {
	if x != nil {
		return x.BreakingDescription
	}
	return ""
}

func (x *ConventionalCommit) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ConventionalCommit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ConventionalCommit) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Artifact represents a file or resource created by a plugin.
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the artifact name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// path is the artifact path (local file or URL).
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// type is the artifact type (file, url, etc.).
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// size is the artifact size in bytes.
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// checksum is the artifact checksum.
	Checksum      string `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// ValidateRequest is the request for validating plugin configuration.
type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config is the plugin configuration as JSON.
	Config        string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ValidateResponse is the response from configuration validation.
type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid indicates if the configuration is valid.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// errors lists validation errors.
	Errors        []*ValidationError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ValidationError represents a configuration validation error.
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field is the field that failed validation.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// message is the error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// code is an optional error code.
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_internal_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\"internal/plugin/proto/plugin.proto\x12\arelicta\"\a\n" +
	"\x05Empty\"\xaf\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x14\n" +
	"\x05hooks\x18\x05 \x03(\tR\x05hooks\x12#\n" +
	"\rconfig_schema\x18\x06 \x01(\tR\fconfigSchema\"\x97\x01\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\x04hook\x18\x01 \x01(\x0e2\r.relicta.HookR\x04hook\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.relicta.ReleaseContextR\acontext\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\xa6\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aoutputs\x18\x04 \x01(\tR\aoutputs\x12/\n" +
	"\tartifacts\x18\x05 \x03(\v2\x11.relicta.ArtifactR\tartifacts\"\xcb\x04\n" +
	"\x0eReleaseContext\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\x02 \x01(\tR\x0fpreviousVersion\x12\x19\n" +
	"\btag_name\x18\x03 \x01(\tR\atagName\x12!\n" +
	"\frelease_type\x18\x04 \x01(\tR\vreleaseType\x12%\n" +
	"\x0erepository_url\x18\x05 \x01(\tR\rrepositoryUrl\x12)\n" +
	"\x10repository_owner\x18\x06 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\a \x01(\tR\x0erepositoryName\x12\x16\n" +
	"\x06branch\x18\b \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\t \x01(\tR\tcommitSha\x12\x1c\n" +
	"\tchangelog\x18\n" +
	" \x01(\tR\tchangelog\x12#\n" +
	"\rrelease_notes\x18\v \x01(\tR\freleaseNotes\x125\n" +
	"\achanges\x18\f \x01(\v2\x1b.relicta.CategorizedChangesR\achanges\x12J\n" +
	"\venvironment\x18\r \x03(\v2(.relicta.ReleaseContext.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x03\n" +
	"\x12CategorizedChanges\x127\n" +
	"\bfeatures\x18\x01 \x03(\v2\x1b.relicta.ConventionalCommitR\bfeatures\x121\n" +
	"\x05fixes\x18\x02 \x03(\v2\x1b.relicta.ConventionalCommitR\x05fixes\x127\n" +
	"\bbreaking\x18\x03 \x03(\v2\x1b.relicta.ConventionalCommitR\bbreaking\x12=\n" +
	"\vperformance\x18\x04 \x03(\v2\x1b.relicta.ConventionalCommitR\vperformance\x127\n" +
	"\brefactor\x18\x05 \x03(\v2\x1b.relicta.ConventionalCommitR\brefactor\x12/\n" +
	"\x04docs\x18\x06 \x03(\v2\x1b.relicta.ConventionalCommitR\x04docs\x121\n" +
	"\x05other\x18\a \x03(\v2\x1b.relicta.ConventionalCommitR\x05other\"\x9b\x02\n" +
	"\x12ConventionalCommit\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1a\n" +
	"\bbreaking\x18\x06 \x01(\bR\bbreaking\x121\n" +
	"\x14breaking_description\x18\a \x01(\tR\x13breakingDescription\x12\x16\n" +
	"\x06issues\x18\b \x03(\tR\x06issues\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\n" +
	" \x01(\tR\x04date\"v\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\")\n" +
	"\x0fValidateRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"Z\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x120\n" +
	"\x06errors\x18\x02 \x03(\v2\x18.relicta.ValidationErrorR\x06errors\"U\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code*\xc2\x02\n" +
	"\x04Hook\x12\x14\n" +
	"\x10HOOK_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rHOOK_PRE_INIT\x10\x01\x12\x12\n" +
	"\x0eHOOK_POST_INIT\x10\x02\x12\x11\n" +
	"\rHOOK_PRE_PLAN\x10\x03\x12\x12\n" +
	"\x0eHOOK_POST_PLAN\x10\x04\x12\x14\n" +
	"\x10HOOK_PRE_VERSION\x10\x05\x12\x15\n" +
	"\x11HOOK_POST_VERSION\x10\x06\x12\x12\n" +
	"\x0eHOOK_PRE_NOTES\x10\a\x12\x13\n" +
	"\x0fHOOK_POST_NOTES\x10\b\x12\x14\n" +
	"\x10HOOK_PRE_APPROVE\x10\t\x12\x15\n" +
	"\x11HOOK_POST_APPROVE\x10\n" +
	"\x12\x14\n" +
	"\x10HOOK_PRE_PUBLISH\x10\v\x12\x15\n" +
	"\x11HOOK_POST_PUBLISH\x10\f\x12\x13\n" +
	"\x0fHOOK_ON_SUCCESS\x10\r\x12\x11\n" +
	"\rHOOK_ON_ERROR\x10\x0e2\xb7\x01\n" +
	"\x06Plugin\x12.\n" +
	"\aGetInfo\x12\x0e.relicta.Empty\x1a\x13.relicta.PluginInfo\x12<\n" +
	"\aExecute\x12\x17.relicta.ExecuteRequest\x1a\x18.relicta.ExecuteResponse\x12?\n" +
	"\bValidate\x12\x18.relicta.ValidateRequest\x1a\x19.relicta.ValidateResponseB7Z5github.com/relicta-tech/relicta/internal/plugin/protob\x06proto3"

var (
	file_internal_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_plugin_proto_rawDescData []byte
)

func file_internal_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_internal_plugin_proto_plugin_proto_rawDescData
}

var file_internal_plugin_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_plugin_proto_plugin_proto_goTypes = []any{
	(Hook)(0),                  // 0: relicta.Hook
	(*Empty)(nil),              // 1: relicta.Empty
	(*PluginInfo)(nil),         // 2: relicta.PluginInfo
	(*ExecuteRequest)(nil),     // 3: relicta.ExecuteRequest
	(*ExecuteResponse)(nil),    // 4: relicta.ExecuteResponse
	(*ReleaseContext)(nil),     // 5: relicta.ReleaseContext
	(*CategorizedChanges)(nil), // 6: relicta.CategorizedChanges
	(*ConventionalCommit)(nil), // 7: relicta.ConventionalCommit
	(*Artifact)(nil),           // 8: relicta.Artifact
	(*ValidateRequest)(nil),    // 9: relicta.ValidateRequest
	(*ValidateResponse)(nil),   // 10: relicta.ValidateResponse
	(*ValidationError)(nil),    // 11: relicta.ValidationError
	nil,                        // 12: relicta.ReleaseContext.EnvironmentEntry
}
var file_internal_plugin_proto_plugin_proto_depIdxs = []int32{
	0,  // 0: relicta.ExecuteRequest.hook:type_name -> relicta.Hook
	5,  // 1: relicta.ExecuteRequest.context:type_name -> relicta.ReleaseContext
	8,  // 2: relicta.ExecuteResponse.artifacts:type_name -> relicta.Artifact
	6,  // 3: relicta.ReleaseContext.changes:type_name -> relicta.CategorizedChanges
	12, // 4: relicta.ReleaseContext.environment:type_name -> relicta.ReleaseContext.EnvironmentEntry
	7,  // 5: relicta.CategorizedChanges.features:type_name -> relicta.ConventionalCommit
	7,  // 6: relicta.CategorizedChanges.fixes:type_name -> relicta.ConventionalCommit
	7,  // 7: relicta.CategorizedChanges.breaking:type_name -> relicta.ConventionalCommit
	7,  // 8: relicta.CategorizedChanges.performance:type_name -> relicta.ConventionalCommit
	7,  // 9: relicta.CategorizedChanges.refactor:type_name -> relicta.ConventionalCommit
	7,  // 10: relicta.CategorizedChanges.docs:type_name -> relicta.ConventionalCommit
	7,  // 11: relicta.CategorizedChanges.other:type_name -> relicta.ConventionalCommit
	11, // 12: relicta.ValidateResponse.errors:type_name -> relicta.ValidationError
	1,  // 13: relicta.Plugin.GetInfo:input_type -> relicta.Empty
	3,  // 14: relicta.Plugin.Execute:input_type -> relicta.ExecuteRequest
	9,  // 15: relicta.Plugin.Validate:input_type -> relicta.ValidateRequest
	2,  // 16: relicta.Plugin.GetInfo:output_type -> relicta.PluginInfo
	4,  // 17: relicta.Plugin.Execute:output_type -> relicta.ExecuteResponse
	10, // 18: relicta.Plugin.Validate:output_type -> relicta.ValidateResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_plugin_proto_init() }
func file_internal_plugin_proto_plugin_proto_init() {
	if File_internal_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_plugin_proto_depIdxs,
		EnumInfos:         file_internal_plugin_proto_plugin_proto_enumTypes,
		MessageInfos:      file_internal_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_plugin_proto = out.File
	file_internal_plugin_proto_plugin_proto_goTypes = nil
	file_internal_plugin_proto_plugin_proto_depIdxs = nil
}
